# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQClxy6bAqXy-wB0ovzaovWpXue6c6XN
"""

def kalkulyator():
    print("Oddiy kalkulyator")
    print("Amallar: 1-Qo'shish, 2-Ayirish, 3-Ko'paytirish, 4-Bo'lish")

    amal = int(input("Amalni tanlang (1-4): "))
    son1 = float(input("1-sonni kiriting: "))
    son2 = float(input("2-sonni kiriting: "))

    if amal == 1:
        natija = son1 + son2
    elif amal == 2:
        natija = son1 - son2
    elif amal == 3:
        natija = son1 * son2
    elif amal == 4:
        if son2 != 0:
            natija = son1 / son2
        else:
            return "Bo'linma nolga teng bo'lishi mumkin emas!"
    else:
        return "Noto'g'ri tanlov!"

    return f"Natija: {natija}"

print(kalkulyator())